user:
    resource: "@UserBundle/Controller"
    type:     annotation

cuisine:
    resource: "@CuisineBundle/Controller/"
    type:     annotation

buvette:
    resource: "@BuvetteBundle/Controller/"
    type:     annotation

login_check:
    path: /login_check

logout:
    path: /logout
