# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        UserBundle\Entity\User: sha512
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity:
                class: UserBundle\Entity\User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                remember_me: false
                success_handler: redirect.after.login
            logout:
                path: logout
                target: /login
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER,ROLE_BUVETTE,ROLE_CUISINE]
        ROLE_BUVETTE: ROLE_USER
        ROLE_CUISINE: ROLE_USER
    access_control:
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/login_check, roles: ROLE_USER }
        - { path: ^/refresh, roles: ROLE_USER }
        - { path: ^/buvette, roles: ROLE_BUVETTE }
        - { path: ^/cuisine, roles: ROLE_CUISINE }
        - { path: ^/admin, roles: ROLE_ADMIN }