<?php

namespace UserBundle\Repository;

/**
 * Produit_panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit_panierRepository extends \Doctrine\ORM\EntityRepository
{
}
